# Generated by Django 4.0.3 on 2022-03-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetail',
            name='testType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDetails.testtype'),
        ),
    ]
