# Generated by Django 4.0.3 on 2022-03-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0002_alter_doctor_photo_alter_patient_photo'),
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttestdetail',
            name='patient',
        ),
        migrations.AddField(
            model_name='patienttestdetail',
            name='patient',
            field=models.ManyToManyField(to='UserLogin.patient'),
        ),
    ]
