# Generated by Django 4.0.3 on 2022-03-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_remove_patienttestdetail_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_By', models.CharField(max_length=50)),
                ('Report_Status', models.CharField(max_length=50)),
                ('Ac_Status', models.CharField(max_length=50)),
                ('onetimetest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.onetimetest')),
            ],
        ),
    ]
